### ISSUE TITLE
to fix errors during first status page data generation

### ISSUE THREAD

**Issue by Ginxo** [kiegroup/chain-status#27]
there's an error about

see this flow https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/main/.github/workflows/generate_status_page_data.yaml and apply to any repository you consider and you will see the flow failing (I remember something about folder not created :thinking: )

Whatever the change we need should be applied on composite action https://github.com/kiegroup/chain-status/blob/main/.ci/actions/generate-data/action.yml

**Comment by lampajr** [comment]
I tried to replicate integrating the `chain-status` tool in a custom project (https://github.com/lampajr/chain-status-example) referring to an external project definition (the kogito one) and I was not able to reproduce the issue.

During the tool integration (aiming to replicate the issue) I wrote a `usage doc` that could be added in the README [PR].

In conclusion I think we can close this issue, do you agree @Ginxo ?

**References**:
[PR] https://github.com/kiegroup/chain-status/pull/31
[Actions] https://github.com/lampajr/chain-status-example/actions
[Status page] https://lampajr.github.io/chain-status-example/status/kogito-status)

**Comment by Ginxo** [comment]
thanks @lampajr
