### ISSUE TITLE
List Github branches bug

### ISSUE THREAD

**Issue by lampajr** [kiegroup/chain-status#39]
It seems there is a bug retrieving the list of branches [1]:
```js
const listBranches = async (
  project,
  octokit,
  options = { page: 1, per_page: 100 }
) => {
  ...
    if (status === 200 && data && data.length > 0) {
      result.push(...data);
      if (data.length === options.per_page) {
        result.push(
          ...(await getChecks(project, octokit, {
            ...options,
            page: ++options.page
 ...
```
As you can see inside `listBranches` we are recursively invoking `getChecks` function, which should be wrong since we are trying to collect the list of branches that exceed the `per_page` param. I think this has never occurred because we quite always have less than 100 branches (I guess).

@Ginxo if you confirm the issue is right, I'll fix it directly in [PR-37](https://github.com/kiegroup/chain-status/pull/37), the one regarding the coverage improvement. 

[1] [code reference](https://github.com/kiegroup/chain-status/blob/main/packages/action/src/lib/git-service.js#L159)

**Comment by Ginxo** [comment]
you are right, it's just a C&P problem... so it's about replacing `getChecks` from #L159 to `listBranches`. Many thanks

https://github.com/kiegroup/chain-status/blob/4ac20d86fcec9d6f94879bef6f3ad614527b03a2/packages/action/src/lib/git-service.js#L159

**Comment by lampajr** [comment]
yeah, exactly! just opened https://github.com/kiegroup/chain-status/pull/40
