### ISSUE TITLE
provide new functionallity to compare branches

### ISSUE THREAD

**Issue by Ginxo** [kiegroup/chain-status#44]
related ticket: https://issues.redhat.com/browse/BAPL-2340

the idea would be to provide branch selection vs branch selection and provide report on the https://kiegroup.github.io/droolsjbpm-build-bootstrap/status/kiegroup-status page
would be nice to set it up with default branches (like 7.67.x vs 7.67.x-blue)
the report should have its own URI in order to share via email or something

**Comment by Ginxo** [comment]
we agreed on:

- from webpage POV
  - 
- from CLI POV
  - new argument for branch comparison
  - same data structure will be kept
  - new field branch-comparison will be added at repository level following format
 
```
{
  main: {"7.67.x": 5, "7.67.x.-bue": 3},
  "7.67.x": {main: 5, "7.67.x.-bue": 0},
  "7.67.x-blue": {"7.67.x": 0, main: 3},
}
```

**Comment by lampajr** [comment]
@Ginxo I agree on getting files data instead of only the number of differences, in this way we can easily still get it (i.e., number of diffs) but for future improvements we already have useful data.
